name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_PREFIX: '"https://recepten-app.herokuapp.com/api"'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build